In [1]:
import pandas as pd
import numpy as np

In [ ]:
from flora_volks import dados_com_gen

#display(dados_com_gen)

In [3]:
dados_com_gen['Número'] = dados_com_gen['Número'].astype('str')
dados_com_gen.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 168 entries, 1 to 177
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Número     168 non-null    object
 1   Família    168 non-null    object
 2   Gênero     168 non-null    object
 3   sp         168 non-null    object
 4   autor      160 non-null    object
 5   Hábito     156 non-null    object
 6   Origem     159 non-null    object
 7   Substrato  150 non-null    object
 8   Endemismo  158 non-null    object
dtypes: object(9)
memory usage: 13.1+ KB

C:\Users\cardi\AppData\Local\Temp\ipykernel_10628\3474883368.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados_com_gen['Número'] = dados_com_gen['Número'].astype('str')

In [4]:
tomboUB = pd.read_excel("tomboUB.xlsx")
tomboUB = tomboUB.rename({'number':'Número'}, axis=1)

indice_col = tomboUB.columns.get_loc('collector')
tomboUB = tomboUB.iloc[:, :indice_col + 1]

tomboUB['Número'] = tomboUB['Número'].astype('str')

print(tomboUB.info())
display(tomboUB)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Número     208 non-null    object
 1   codbarras  208 non-null    object
 2   numtombo   208 non-null    int64
 3   collector  208 non-null    object
dtypes: int64(1), object(3)
memory usage: 6.6+ KB
None

    Número  codbarras  numtombo          collector
0        1  UB0328376    234756       Ferreira, IP
1        2  UB0328377    234757       Ferreira, IP
2        3  UB0328378    234758       Ferreira, IP
3        4  UB0328379    234759       Ferreira, IP
4        5  UB0328380    234760       Ferreira, IP
..     ...        ...       ...                ...
203   3135  UB0326336    232718  Carvalho-Silva, M
204   3136  UB0326337    232719  Carvalho-Silva, M
205   3137  UB0326338    232720  Carvalho-Silva, M
206   3138  UB0326339    232721  Carvalho-Silva, M
207   77-B  UB0331062    237427       Ferreira, IP

[208 rows x 4 columns]

In [5]:
dados_com_gen = dados_com_gen.merge(tomboUB, on = 'Número', how='left')

In [17]:
#Agrupas por espécies e agregar número de coletor e codbarras
columns = ['Família','Gênero','sp','autor','Hábito','Origem','Substrato','Endemismo','collector']

dados_agr_rel = dados_com_gen.groupby(columns).agg({'Número': ', '.join, 'codbarras': ', '.join}).reset_index()
#dados_agr_rel = dados_com_gen.groupby(columns).agg({'Número': ', '.join}).reset_index()

display(dados_agr_rel)

,Família,Gênero,sp,autor,Hábito,Origem,Substrato,Endemismo,collector,Número,codbarras
0,Acanthaceae,Justicia,chrysotrichoma,(Nees) Benth.,"Erva, Subarbusto",Nativa,Terrícola,sim,"Ferreira, IP",24,UB0328399
1,Alstroemeriaceae,Altroemeria,stenopetala,Schenk,Erva,Nativa,Terrícola,sim,"Ferreira, IP",138,UB0330935
2,Amaranthaceae,Pfaffia,denudata,(Moq.) Kuntze,"Arbusto, Erva, Subarbusto",Nativa,Terrícola,sim,"Ferreira, IP","21, 169","UB0328396, UB0330966"
3,Anacardiaceae,Tapirira,guianensis,Aubl.,Árvore,Nativa,Terrícola,não,"Ferreira, IP",142,UB0330939
4,Annonaceae,Annona,tomentosa,R.E.Fr.,"Arbusto, Subarbusto",Nativa,Terrícola,não,"Ferreira, IP",42,UB0328417
...,...,...,...,...,...,...,...,...,...,...,...
115,Thelypteridaceae,Christella,hispidula,(Decne.) Holttum,Erva,Nativa,Terrícola,não,"Ferreira, IP",166,UB0330963
116,Urticaceae,Cecropia,pachystachya,Trécul,Árvore,Nativa,Terrícola,não,"Ferreira, IP",90,UB0328465
117,Verbenaceae,Lippia,stachynoides var. martiana,(Schauer) Salimena & Múlgura,"Arbusto, Subarbusto",Nativa,Terrícola,sim,"Ferreira, IP",39,UB0328414
118,Verbenaceae,Lippia,vernonioides,Cham.,Arbusto,Nativa,Terrícola,sim,"Ferreira, IP",157,UB0330954
119,Verbenaceae,Stachytarpheta,villosa,(Pohl) Cham.,Arbusto,Nativa,Terrícola,sim,"Ferreira, IP","1, 36","UB0328376, UB0328411"

In [15]:
dados_agr_rel = dados_agr_rel.sort_values(by=['Família','Gênero','sp'])
dados_agr_rel.loc[dados_agr_rel.Família == 'Piperaceae']

,Família,Gênero,sp,autor,Hábito,Origem,Substrato,Endemismo,collector,Número,codbarras
91,Piperaceae,Piper,aduncum,L.,"Arbusto, Árvore",Nativa,Terrícola,não,"Carvalho-Silva, M",3135,UB0326336
92,Piperaceae,Piper,aduncum,L.,"Arbusto, Árvore",Nativa,Terrícola,não,"Ferreira, IP",104,UB0328479
93,Piperaceae,Piper,macedoi,Yunck.,Arbusto,Nativa,Terrícola,sim,"Ferreira, IP",117,UB0328492
94,Piperaceae,Piper,tectoniifolium,Kunth.,Arbusto,Nativa,Terrícola,sim,"Carvalho-Silva, M",3130,UB0326331

In [ ]:
dados_agr_rel['Espécie'] = dados_agr_rel['Gênero'].str.cat(dados_agr_rel['sp'], sep=" ").str.cat(dados_agr_rel['autor'],sep=" ")
drop_columns = ['sp','Gênero','autor']
dados_agr_rel = dados_agr_rel.drop(labels=drop_columns, axis=1)

In [ ]:
new_column_order = ['Número', 'Família', 'Espécie','Hábito','Origem','Substrato','Endemismo','codbarras','collector']
dados_agr_rel = dados_agr_rel.reindex(columns=new_column_order)
print(dados_agr_rel)

display(dados_agr_rel)

In [18]:
dados_agr_rel['collector'].unique()

array(['Ferreira, IP', 'Carvalho-Silva, M'], dtype=object)

In [19]:
dados_agr_rel = dados_agr_rel.replace({'Ferreira, IP':'Ferreira, IP et al.','Carvalho-Silva, M':'Carvalho-Silva, M et al.'})

In [38]:
nome_arquivo_excel = 'FloraVolks_apendiceA.xlsx'

dados_agr_rel.to_excel(nome_arquivo_excel, index=False)